version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - "./contracts/:/app/contracts/"
      - "./test/:/app/test/"
      - "./scripts/:/app/scripts/"
