version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: ["yarn", "hardhat", "node"]
    env_file:
      - .env
    volumes:
      - "./artifacts/:/app/artifacts/"
      - "./contracts/:/app/contracts/"
      - "./test/:/app/test/"
      - "./scripts/:/app/scripts/"
    ports:
      - '8545:8545'
